### PR TITLE
Fix build type check error

### LINKED ISSUE #133: Build fails on type checking
### Describe the bug

`yarn build` command fails on type checking because the generated GraphQL types strip out characters and there is now a duplicate for `Owners` on the `Token_OrderBy` (corresponding to the internal `_owners` and public `owners` fields in the Subgraph)

See similar issue raised in the `graphql-code-generator` repo: https://github.com/dotansimha/graphql-code-generator/issues/642

Solution is to reconfigure the enum naming conventions:
```
config:
  namingConvention:
    enumValues: keep
```

### Steps to reproduce

1. Check out the `main` branch
2. Run `yarn build`

### Expected behavior

As a developer, I expected the project to build, but it resulted in a type checking error

### How often does this bug happen?

Every time

### Screenshots or Videos

_No response_

### Platform

- OS: any
- Browser: none
- Version: `main` branch as of January 26, 2022

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by alecananian**
Fixes #133 (broken build command) by updating the GraphQL codegen config

@wyze @jcheese1

### CODE REVIEW

**Comment by wyze** [comment]
Thanks @alecananian! I know I had something locally, that fixed this but used a different settings and never committed. Do you want to fix the build errors that this change introduces?

**Comment by alecananian** [comment]
@wyze whoops, did not realize there were build errors as a result! Fixed those now.

**Comment by wyze** [comment]
Awesome, thank you!

**Comment by wyze** [comment]
@allcontributors add @alecananian for code

**Pull request merged**
