### PR TITLE
Update marketplace to work with newer subgraph

### PR DESCRIPTION
**Pull request by wyze**
A bunch to do here still but shouldn't be terrible.

TODO:

- [x] Pull metadata from current marketplace subgraph
	- I added `getMetadata` to client queries, but is bringing back 0 results for some reason.. Works fine in GraphQL explorer.
- [x] Get metadata (images/names) working properly on collection listings pagee
- [x] Handle staked tokens in user inventory (user.staked) [for smol brains/bodies]
- [x] Handle listed tokens in user inventory
- [x] Activity tab on collection page
- [x] Treasure description in Inventory shows "Legion" not "Treasures"
- [x] Filters Smol Brains/Bodies
- [x] Messaging on Legacy Legions/Genesis Legions pages
- [x] Fix flicker on applying filter
- [x] Fix duplicate ERC1155 listings
- [x] Fix name filter

### CODE REVIEW

**Comment by magiclars-off** [comment]
Issue seems to be in the `where` clause, without it, it returns data.

At other places I see usage of this clause => `tokens(first: 200, where: { contract: $id })` 
That seems to work.

**Comment by magiclars-off** [comment]
Maybe id should be of type ID! instead of string  => `query getMetadata($id: **String!**)` 

Id in collection is of that type `id: Scalars['ID'];`

I tried removing the where-clause, then the query does return data

**Comment by wyze** [comment]
> Maybe id should be of type `ID` instead of `String` => `query getMetadata($id: String!)`
> 
> Id in collection is of that type `id: Scalars['ID'];`
> 
> I tried removing the where-clause, then the query does return data

Thanks @magiclars-off . When running locally, I was actually trying to match up production collections from new subgraph with the metadata from my marketplace-dev subgraph! I forgot to change my environment variables to point to the production marketplace subgraph.

I see the images working on the deployed branch here on Vercel, as expected though!

**Comment by jcheese1** [comment]
- [ ] Handle filter

**Pull request merged**
