### PR TITLE
Add Dynamic Metadata to pages

### LINKED ISSUE #99: Add proper title for collection + token details page
We currently don't have proper titles for each token page + collection page. Can be separate PRs but would be great if we can have these, for SEO purposes and visibility when you link.

### PR DESCRIPTION
**Pull request by magiclars-off**
resolves #99 

This implementation removes the generic `Head` and allows you to add specific `metadata` per page.
All `props` are optional and fallbacks back to current metadata.

note:
Would be nice is to add functionality to add a specific `description` per collection which can be added to the `collection`-page and added to the metadata.

### CODE REVIEW

**Comment by wyze** [comment]
Gotcha! We can track that here: https://github.com/TreasureProject/treasure-marketplace-subgraph/issues/50

**Comment by jcheese1** [comment]
will this conflict with #103 ? @federivo

**Comment by magiclars-off** [comment]
It does. It seems like #103 does not setting the default `og` & `twitter` metadata, resulting in the default twitter card

image

**Comment by magiclars-off** [comment]
Rebased this one

**Comment by magiclars-off** [comment]
Is this one still relevant @jcheese1?

To test this I used, [Localhost OPG Checker](https://chrome.google.com/webstore/detail/localhost-open-graph-chec/gcbnmkhkglonipggglncobhklaegphgn?hl=en)
it's a Chome plugin which let you validate Twitter Cards on localhost.

**Comment by wyze** [comment]
Thanks @magiclars-off! Sorry for the massive delay. But, we got those collection descriptions now.

**Pull request merged**
