### PR TITLE
Focus search input when search icon clicked

### LINKED ISSUE #229: Search Icon does not put input in focus on click
### Describe the bug

Search Icon only is a visual indicator. Search icon should at least put focus to the input associated when clicked. Most patterns on other websites have event behaviors.

### Steps to reproduce

1. Click on search icon

### Expected behavior

1. Autocomplete dropdown AND focus on input

### How often does this bug happen?

_No response_

### Screenshots or Videos

https://user-images.githubusercontent.com/30575095/161368188-8ada612f-56e4-4b0d-b141-d9c6ef7d1535.mov

### Platform

- OS: [e.g. macOS, Windows, Linux, iOS, Android]
- Browser: [e.g. Chrome, Safari, Firefox, React Native]
- Version: [e.g. 91.1]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by caesarTheApe**
This PR closes #229

### CODE REVIEW

**Comment by wyze** [comment]
Thanks for this, but the issue you are linking to describes the problem as clicking the search icon doesn't bring focus to the input. This PR still has that issue as it only changed the color of the icon on focus.

**Comment by caesarTheApe** [comment]
Thanks for the review @wyze. I misunderstood the issue, mb. 

Now I am focusing the input when clicking the search icon. I also kept the color changed, but can remove if you think it is necessary.

**Review by wyze — APPROVED** [review]
Great, thanks!

**Comment by wyze** [comment]
@allcontributors add @caesarTheApe for code

**Pull request merged**
