### PR TITLE
Toggle GridSize on large screens

### PR DESCRIPTION
**Pull request by magiclars-off**
Allow users of large screens to toggle grid size. 

Saw people on twitter share css hacks to increase grid size, so think this is a welcoming addition

image

@wyze @jcheese1

### CODE REVIEW

**Comment by wyze** [comment]
@magiclars-off Can you fix the build failure please?

**Comment by wyze** [comment]
@magiclars-off Is it expected to not do anything for collections without filters? Currently the pets collections or Consumables. Feel like we should hide it or make it do something, as currently when I click it on those, the icon changes but nothing else happens.

**Comment by magiclars-off** [comment]
@wyze, I missed that one. Thank you for pointing out.

- I removed the Toggle for collections without filters, else the code gets pretty nasty.
- slightly reduced the subtext on Legions so it fits on larger gridsize 
- Inverted the GridToggle icon, I think it should display the current size (not sure what you guys prefer)

image

**Comment by alecananian** [comment]
I'll test again when the latest updates are pushed to the Vercel preview site, but right now these changes are reverting #179. I agree the 4 column grid on very large screens is a strange UI, though. Couldn't we resolve that with a `2xl:grid-cols-6` class instead of needing the toggle?

**Comment by alecananian** [comment]
So the latest changes fix things a bit, but still got some weirdness on 1280x800 (which in Tailwind world is `xl`):

Screen Shot 2022-02-18 at 8 51 06 AM

**Review by wyze — APPROVED** [review]
I think this looks good. Can iterate on it if needed.

**Pull request merged**
