### PR TITLE
Change page titles for collection and token pages

### PR DESCRIPTION
**Pull request by federivo**
Fix for #99

### CODE REVIEW

**Review by wyze — CHANGES_REQUESTED** [review]
Sorry for the late review, but can we add some kind of template, like `<Collection> | Treasure Marketplace` and `<ID/Name> - <Collection> | Treasure Marketplace`? Otherwise looks great!

**Comment by federivo** [comment]
> Sorry for the late review, but can we add some kind of template, like `<Collection> | Treasure Marketplace` and `<ID/Name> - <Collection> | Treasure Marketplace`? Otherwise looks great!

For sure, on it!

**Comment by federivo** [comment]
@wyze done :smile: 

Let me know if changes are good or if there is anything else you want to change. Thanks!

**Comment by wyze** [comment]
Thanks, but I believe this is solved now.

**Pull request closed without merging**
