### PR TITLE
Change Home icon to Treasure Logo

### LINKED ISSUE #202: Home icon on desktop view should be treasure logo
### Describe the bug

The pattern of the website logo on the top left as home navigation is on many websites. I think the intent is to promote branding. 

### Steps to reproduce

1. View header on marketplace on desktop view.

### Expected behavior

1. Treasure logo appears instead of home icon.

### How often does this bug happen?

_No response_

### Screenshots or Videos

Screen Shot 2022-03-18 at 8 19 20 AM

### Platform

- OS: [e.g. macOS, Windows, Linux, iOS, Android]
- Browser: [e.g. Chrome, Safari, Firefox, React Native]
- Version: [e.g. 91.1]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by davidagustin**
Verified Locally

https://user-images.githubusercontent.com/30575095/159117669-77778c27-3450-4795-8b68-598fce4b3c04.mov

Fixes #202

### CODE REVIEW

**Comment by magiclars-off** [comment]
I would extract the `svg` into a separate component and allow to pass props (e.g. color, dimensions etc.). Would improve reusability.

**Comment by davidagustin** [comment]
> I would extract the `svg` into a separate component and allow to pass props (e.g. color, dimensions etc.). Would improve reusability.

Ahh I see, there is a special Icon folder for this. Thankyou for your recommendation.

**Comment by davidagustin** [comment]
#199 Should be merged first to update the footer logo because it is the exact same logo in this commit.

**Comment by wyze** [comment]
Thanks @magiclars-off and @davidagustin!

**Pull request merged**
